version: '2'
services:
  drupal:
    # Set here the hostname by which you will access the docker container. Use
    # a unique name, ending with `.docker.amazee.io`
    hostname: &hostname changeme.com.docker.amazee.io

    environment:

      # If you would like to use blackfire.io, uncomment and add your server credentials:
      #BLACKFIRE_SERVER_ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      #BLACKFIRE_SERVER_TOKEN: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

      # If you want to use stage_file_proxy, uncomment following line and add the production url of your website:
      #AMAZEEIO_PRODUCTION_URL: 'http://example.com'

      # APC Support is by default enabled, but in some cases it can make issues, change to 0 to disable:
      APC: 1

      VIRTUAL_HOST: *hostname

      # If index.php is not in the root of your repo, uncomment and set the
      # webroot directory here, for composer projects this is usually 'web'
      # WEBROOT: web

    # choose which version of php you will use by setting the image. Current options
    # are 'amazeeio/drupal:php56-basic' and 'amazeeio/drupal:php70-basic'
    image: amazeeio/drupal:php56-basic
    volumes:
      - .:/var/www/drupal/public_html:delegated
    volumes_from:
      - container:amazeeio-ssh-agent
    container_name: *hostname
    ports:
      - 3306
    networks:
      - amazeeio-network
      - default
  solr:
    image: amazeeio/solr:5  # allowed solr versions are 3/5/6
    ports:
      - 8983

networks:
  amazeeio-network:
    external: true
